project:
  type: website
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
    - "!files/"

website:
  title: "Gov 50"
  favicon: "files/img/gov50-icon-512.png"
  navbar:
    pinned: true
    background: "#3498db"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Materials"
        file: materials/index.qmd
      - text: "Assignments"
        file: assignments/index.qmd
      - text: "Resources"
        file: resources/index.qmd
      - text: "Ed"
        href: https://edstem.org/us/courses/24957/discussion/
      - text: "Gradescope"
        href: https://www.gradescope.com/courses/415456

  sidebar:
    - title: "Materials"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Overview"
          contents:
            - materials/index.qmd
        - section: "Course Materials"
          contents:
            - text: "0: Introduction to Gov 50"
              file: materials/01_intro.qmd
            - text: "1: R, RMarkdown and Data Visualization"
              file: materials/02_r_data_viz.qmd
            - text: "2: Data Wrangling"
              file: materials/03_data_wrangling.qmd
            - text: "3: Causality"
              file: materials/04_causality.qmd
            - text: "4: Summarizing and Measurement"
              file: materials/05_measurement.qmd
            - text: "5: Relationships, Functions, and Importing/Tidying Data"
              file: materials/06_bivariate_tidying.qmd
              
    - title: "Assignments"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Resources"
          contents:
            - assignments/index.qmd
            - assignments/tutorials.qmd
            - assignments/problem-sets.qmd
        - section: "Assignments"
          contents:
            - text: "Problem Set 0"
              file: assignments/00-problem-set.qmd
            - text: "Problem Set 1"
              file: assignments/01_hw_data_viz.qmd
            - text: "Problem Set 2"
              file: assignments/02_hw_data_wrangling.qmd
            - text: "Problem Set 3"
              file: assignments/03_hw_causality.qmd
            - text: "Problem Set 4"
              file: assignments/04_hw_summarizing.qmd
format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true

execute:
  freeze: auto



