project:
  type: website

website:
  title: "Gov 50"
  favicon: "files/img/gov50-icon-512.png"
  navbar:
    pinned: true
    background: "#3498db"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Materials"
        file: materials/index.qmd
      - text: "Assignments"
        file: assignments/index.qmd
      - text: "Ed"
        href: https://edstem.org/us/courses/24957/discussion/
      - text: "Gradescope"
        href: https://www.gradescope.com/courses/415456

  sidebar:
    - title: "Materials"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Overview"
          contents:
            - materials/index.qmd
        - section: "Course Materials"
          contents:
            - text: "0: Introduction to Gov 50"
              file: materials/01_intro.qmd
            - text: "1: R, RMarkdown and Data Visualization"
              file: materials/02_r_data_viz.qmd

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true

execute:
  freeze: auto



