project:
  type: website

website:
  title: "Gov 50"
  navbar:
    pinned: true
    background: "#3498db"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Assignments"
        file: assignments/index.qmd

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true



